version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    restart: unless-stopped
    ports: ["6379:6379"]

  python-backend:
    build: ./backend
    env_file:
      - ./server/.env
      - ./backend/.env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./server/uploads:/app/uploads
    ports:
      - "5001:5001"

  celery-worker:
    build: ./backend
    env_file:
      - ./server/.env
      - ./backend/.env
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - python-backend
      - redis
      - mongo

  server:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3001:3000"
    depends_on:
      - server

volumes:
  mongo_data:
